# Use the official Node.js 20 LTS base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Clone the repository
COPY myapp/package.json .

# Install the application dependencies
RUN npm install

# Copy Remaining Code
COPY myapp/* .

# Update .env Variable
RUN cp myapp/env .env


# Expose the application port (assuming app.js uses port 3000)
EXPOSE 3000

# Start the application
CMD ["node", "app.js"]


