apiVersion: v1
kind: Service
metadata:
  name: gcpnodeapp-service
  labels:
    app: gcpnodeapp
spec:
  type: LoadBalancer
  selector:
    app: gcpnodeapp
  ports:
    - port: 3000           # Port exposed by the LoadBalancer
      targetPort: 3000   # Port on which the application is running inside the container
